name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.11.0
        with: { clang-format-version: "15" }
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install blender python-is-python3 -y
      - uses: actions/checkout@v4
      - run: bazel build --config=ci ...
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: Cyberboss/install-winget@v1
      - run: winget upgrade --accept-source-agreements
      - run: winget install BlenderFoundation.Blender --disable-interactivity
      - name: bazel visual studio 17.6 workaround # https://github.com/bazelbuild/bazel/issues/18592
        run: Remove-Item -Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg" -Force -Recurse
      - uses: actions/checkout@v4
      - run: bazel build --config=ci //...
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install blender python-is-python3 -y
      - uses: actions/checkout@v4
      - run: ./CheckDist.sh
