name: Release

# on:
#   push:
#     tags:
#       - "[0-9]+.[0-9]+.[0-9]+"
#       - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

# TODO(zaucy): remove branch push when testing is done
on:
  push:
    branches:
      - "**"

jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1

  common-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v3
      - run: ./copy_common_dist.sh
      - uses: actions/upload-artifact@v3
        with:
          name: common-dist
          path: dist
  windows-x64-binaries:
    runs-on: windows-latest
    steps:
      - name: Get Home Directory
        id: get_home_dir
        run: echo "::set-output name=dir::$HOME"
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v3
      - run: bazel run --config=ci //:copy_dist_bin
      - run: bazel run --config=ci //:copy_dist_codegen_plugins
      - uses: actions/upload-artifact@v3
        with:
          name: windows-x64-binaries
          path: dist
  linux-x64-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v3
      - run: bazel run --config=ci //:copy_dist_bin
      - run: bazel run --config=ci //:copy_dist_codegen_plugins
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64-binaries
          path: dist

  linux-x64-archive:
    runs-on: ubuntu-latest
    needs:
      - linux-x64-binaries
      - common-dist
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: common-dist
      - uses: actions/download-artifact@v3
        with:
          name: linux-x64-binaries
      - run: tar -czf ecsact_sdk_${{github.ref_name}}_linux_x64.tar.gz bin include
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64-archive
          path: ecsact_sdk_${{github.ref_name}}_linux_x64.tar.gz

  windows-x64-archive:
    runs-on: ubuntu-latest
    needs:
      - windows-x64-binaries
      - common-dist
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: common-dist
      - uses: actions/download-artifact@v3
        with:
          name: windows-x64-binaries
      - run: >
          mv bin/ecsact-rtb.runfiles bin/ecsact-rtb.exe.runfiles &&
          zip -r ecsact_sdk_${{github.ref_name}}_windows_x64.zip bin include
      - uses: actions/upload-artifact@v3
        with:
          name: windows-x64-archive
          path: ecsact_sdk_${{github.ref_name}}_windows_x64.zip

  release-upload-linux-x64-archive:
    runs-on: ubuntu-latest
    needs:
      - release-draft
      - linux-x64-archive
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: linux-x64-archive
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: ecsact_sdk_${{github.ref_name}}_linux_x64.tar.gz

  release-upload-windows-x64-archive:
    runs-on: ubuntu-latest
    needs:
      - release-draft
      - windows-x64-archive
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: windows-x64-archive
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: ecsact_sdk_${{github.ref_name}}_windows_x64.zip

  release-finish:
    runs-on: ubuntu-latest
    needs:
      - release-upload-windows-x64-archive
      - release-upload-linux-x64-archive
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          name: ${{github.ref_name}}
          generate_release_notes: true
